version: '2'

services:
  master:
    image: lewuathe/hadoop
    ports:
      - "9000:9000"
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "master"
    environment:
      - MASTER
  slave1:
    image: lewuathe/hadoop
    container_name: "slave1"
    ports:
      - "9901:9864"
      - "8041:8042"
    environment:
      - SLAVE
  slave2:
    image: lewuathe/hadoop
    container_name: "slave2"
    ports:
      - "9902:9864"
      - "8042:8042"
    environment:
      - SLAVE
  slave3:
    image: lewuathe/hadoop
    container_name: "slave3"
    ports:
      - "9903:9864"
      - "8043:8042"
    environment:
      - SLAVE
  slave4:
    image: lewuathe/hadoop
    container_name: "slave4"
    ports:
      - "9904:9864"
      - "8044:8042"
    environment:
      - SLAVE
  slave5:
    image: lewuathe/hadoop
    container_name: "slave5"
    ports:
      - "9905:9864"
      - "8045:8042"
    environment:
      - SLAVE
